debug: false
spring:
  application:
    name: amaranth
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  main:
    banner-mode: OFF
  docker:
    compose:
      enabled: false
  profiles:
    active: dev
discord:
  testGuildID: ${TEST_GUILD_ID}
  token: ${BOT_TOKEN}
  activity: "Say /ping"
